name: universal_ntp
description: Fetch accurate time or current DateTime object from (NTP) Network Time Protocol server.
version: 1.0.8
homepage: https://github.com/knezzz/ntp

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  universal_io: ^2.0.4
